name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code
        uses: actions/checkout@v1
      - name: install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
      - name: install gofmt
          go install golang.org/x/tools/cmd/gofmt@latest
      - name: Run Unit tests.
        run: |
          go test -v ./...
