name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.16', '1.17', '1.18' ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3
      - name: install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Run Unit tests.
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go test -v ./...
